version: '3'

services:
  jira:
    build:
      context: .
      dockerfile: ./jira/Dockerfile
    depends_on:
      - mysql
    container_name: jira
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./data/jira:/var/atlassian/jira  # JIRA_HOME

  mysql:
    container_name: mysql  # https://store.docker.com/images/mysql
    restart: always
    image: mysql:5.7
    environment:
      # Use a .env file to store credentials securely?
      # https://docs.docker.com/compose/environment-variables/
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=jiradb          # this database will be created on image startup
      - MYSQL_USER=jira                # this user will be granted superuser permissions on MYSQL_DATABASE
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DEFAULT_STORAGE_ENGINE=INNODB
      - CHARACTER_SET_SERVER=utf8mb4
    ports:
      - '3306:3306'
    command:
      - --default-storage-engine=INNODB
      - --character-set-server=utf8mb4
      - --innodb_default_row_format=DYNAMIC
      - --innodb_large_prefix=on
      - --innodb_file_format=Barracuda
      - --innodb_log_file_size=2GB
      - --sql_mode=NO_AUTO_VALUE_ON_ZERO
    volumes:
      - ./data/mysql:/var/lib/mysql

volumes:
  jira-data:
  mysql-data: